name: Postman Collection

on:
  workflow_dispatch:
  push:
    branches:
      - feature/gitHubActionsAssignmentOne
  pull_request:
    branches:  
      - feature/gitHubActionsAssignmentOne

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: feature/gitHubActionsAssignmentOne    

      - name: Install Newman
        run: npm install -g newman
        
      - name: Install Newman HTML Extra Reporter  
        run: npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: newman run Collection_Assertion.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export postman.html

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: postman-report
          path: postman.html
          retention-days: 30 
